//
// Created by zhihui on 20-11-5.
//

#ifndef GRASS_PATH_PLANNER_PREFIX_ERRNO_H
#define GRASS_PATH_PLANNER_PREFIX_ERRNO_H

#define COVERAGE_ERROR_INIT 10;
#define COVERAGE_ERROR_COVERAGE_PATH_FAIL_TO_PLAN 11;
#define COVERAGE_ERROR_SUBREGION_CONNECT_PATH_FAIL_TO_PLAN 12;
#define COVERAGE_ERROR_WELT_PATH_FAIL_TO_PLAN 13;
#define COVERAGE_ERROR_INIT_POINT_IS_NOT_SAFE 14;
#define COVERAGE_ERROR_COVERAGE_START_POINT_IS_NOT_SAFE 15;
#define COVERAGE_ERROR_INIT_POINT_TO_COVERAGE_START_PATH_FAIL_TO_PLAN 16;
#define COVERAGE_ERROR_PATH_FAIL_TO_CONVERT_VECTOR 17;

#define DIFF_GLOBAL_ERROR_INIT_POINT_IS_NOT_SAFE 20;
#define DIFF_GLOBAL_ERROR_GOAL_POINT_IS_NOT_SAFE 21;
#define DIFF_GLOBAL_ERROR_ASTAR_PATH_FAIL_TO_PLAN 22;
#define DIFF_GLOBAL_ERROR_PRM_PATH_FAIL_TO_PLAN 23;

#endif //GRASS_PATH_PLANNER_PREFIX_ERRNO_H
